name: products
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  json_serializable: ^6.6.1
  google_fonts: ^6.2.1
  syncfusion_flutter_charts : ^25.1.38
  flutter_localization: ^0.2.0
  shared_preferences: ^2.2.2
  flutter_image: ^4.1.11
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  
